version: '3'

services:
  bgpa-server:
    build:
      context: .
      args:
        JAR_FILE: bgg-profile-analyzer-0.0.1-SNAPSHOT.jar
    expose:
      - "8080"
    ports:
      - "80:8080"
    networks:
      - redis-net
    links:
      - "redis-server:redis"
    depends_on:
      - redis-server


  redis-server:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:
    driver: bridge

volumes:
  redis-data: